build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.19
  amd64: ghcr.io/home-assistant/amd64-base:3.19
labels:
  org.opencontainers.image.title: "Tududi"
  org.opencontainers.image.description: "Self-hosted task management for Home Assistant"
  org.opencontainers.image.source: "https://github.com/woytekbode/addons-tududi"
  org.opencontainers.image.licenses: "MIT"
